apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-actuator
spec:
#  replicas: 1
  template:
    spec:
      containers:
        - name: demo-actuator
          resources:
            requests:
              cpu: "0.3"
              memory: "128m"
            limits:
              cpu: "0.5"
              memory: "256m"
          env:
            - name: spring.config.location
              value: classpath:application.yml,file:/app/config/application.yml
            - name: BPL_JVM_HEAD_ROOM
              value: "2"
            - name: BPL_JVM_LOADED_CLASS_COUNT
              value: "35"
            - name: BPL_JVM_THREAD_COUNT
              value: "10"
            - name: JAVA_OPTS
              value: >-
                -XX:ReservedCodeCacheSize=40M
                -XX:MaxMetaspaceSize=60M
                -Xlog:gc
                -Xms34m
                -Xmx40m
                -Xss256k
                -XX:MaxRAM=150M