apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: demo-actuator
resources:
  - deployment.yml
#patchesStrategicMerge:
#  - patch/memorylimit_patch.yml
configMapGenerator:
  - name: demo-actuator-config
    files:
      - config/application.yml